services:
  db:
    image: postgres:15-alpine
    container_name: sso-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sso_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  db_test:
    image: postgres:15-alpine
    container_name: sso-db-test
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sso_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
  postgres_test_data:
